# Generated by Django 4.1.6 on 2023-02-06 16:39

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Phone',
            fields=[
                ('phone_name', models.CharField(blank=True, max_length=60, null=True)),
                ('phone_price', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True)),
                ('phone_review', models.TextField(blank=True, max_length=1000, null=True)),
                ('phone_id', models.AutoField(primary_key=True, serialize=False)),
                ('phone_image', models.ImageField(upload_to='phone/')),
            ],
        ),
    ]
