# Generated by Django 4.1.6 on 2023-02-14 17:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('kevinPhone', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Contact',
            fields=[
                ('contact_id', models.AutoField(primary_key=True, serialize=False)),
                ('contact_name', models.CharField(max_length=60)),
                ('contact_surname', models.CharField(blank=True, max_length=60, null=True)),
                ('contact_email', models.EmailField(blank=True, max_length=254, null=True)),
            ],
        ),
    ]
