# Generated by Django 4.1.6 on 2023-02-16 00:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('kevinPhone', '0004_alter_contact_contact_pass1_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='contact',
            name='contact_pass1',
        ),
        migrations.RemoveField(
            model_name='contact',
            name='contact_pass2',
        ),
        migrations.AddField(
            model_name='contact',
            name='contact_message',
            field=models.TextField(blank=True, max_length=1000, null=True),
        ),
    ]
