# Generated by Django 4.1.6 on 2023-02-16 18:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('kevinPhone', '0005_remove_contact_contact_pass1_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='phone',
            name='product_description',
            field=models.TextField(blank=True, max_length=1000, null=True),
        ),
    ]
