# Generated by Django 4.1.6 on 2023-02-18 16:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('kevinPhone', '0006_phone_product_description'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='phone',
            name='product_description',
        ),
    ]
